version: '3'

services:
  app:
    container_name: "app-calculadora"
    user: node
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: sh -c "yarn install && yarn start"