version: '3'

services:
  app:
    container_name: "app-calculator"
    build: .
    command: sh -c "yarn install && yarn serve"
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app